# Generated by Django 5.1.1 on 2024-10-05 20:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="GeologicalFeature",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("x_coordinate", models.FloatField()),
                ("y_coordinate", models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name="LifeForm",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("discovered", models.BooleanField(default=False)),
                (
                    "geological_feature",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="explorer.geologicalfeature",
                    ),
                ),
            ],
        ),
    ]
